var geojson_MetroWestProperties = {
"type": "FeatureCollection",
"crs": { "type": "name", "properties": { "name": "urn:ogc:def:crs:OGC:1.3:CRS84" } },
"features": [
{ "type": "Feature", "properties": { "Property": "St. Joseph Hall", "Status": "In operation", "Number of Units": 25.0, "Description": "This historic building located at 2 Rosary Drive in Watertown is currently home to 25 elderly tenants, but was the Rosary High School for over 50 years. It is part of an educational campus that was established by the Dominican Sisters of Peace in 1911 and has evolved into a multi-generational community of rental apartments, condominiums and a 45 student pre-school. The project received $5.5 million in financing support from the Town of Watertown, the Mass Dept. of Housing and Community Dev., the Community Economic Development Assistance Corp., the Mass Housing Investment Corp., the Federal Home Loan Bank of Boston, the Marshall Homes Fund, and Watertown Savings Bank.", "Tenancy": "Rent", "Address": "2 Rosary Drive, Watertown, MA 02472", "Latitutde": 42.374435, "Longitude": -71.194838 }, "geometry": { "type": "Point", "coordinates": [ -71.194838, 42.374435 ] } },
{ "type": "Feature", "properties": { "Property": "1060 Belmont", "Status": "In operation", "Number of Units": 18.0, "Description": "This acquisition\/rehabilitiation undertaking of the organization. Over $5.5 million was raised from the Town of Watertown, Federal Home Loan Bank, Community Economic Development Assistance Corporation and Low Income Housing Tax Credits awarded by the Mass. Dept. of Housing and Community Development. Other key partners include Boston Community Capital and Watertown Savings Bank. The project provides 18 units to families earning less than 60% of area median income or about $58,000 for a family of four.", "Tenancy": "Rent", "Address": "1060 Belmont Street, Watertown, MA 02472", "Latitutde": 42.382138, "Longitude": -71.197242 }, "geometry": { "type": "Point", "coordinates": [ -71.197242, 42.382138 ] } },
{ "type": "Feature", "properties": { "Property": "28 Quimby", "Status": "In operation", "Number of Units": 1.0, "Description": "The redevelopment of two 2-family homes into four affordable condominiums was the organization’s first effort a housing development. Key partners include the Mass. Dept. of Housing and Community Development and Belmont Savings Bank. Its total development cost was $1.2 million", "Tenancy": "Rent", "Address": "28 Quimby Street, Watertown, MA 02472", "Latitutde": 42.367326, "Longitude": -71.160775 }, "geometry": { "type": "Point", "coordinates": [ -71.160775, 42.367326 ] } },
{ "type": "Feature", "properties": { "Property": "40 River", "Status": "In Progress", "Number of Units": 18.0, "Description": "Metro West CD was recently designated as the developer of a town-owned site in Norwell. In the fall of 2015 the Norwell Community Housing Trust put out a Request for Proposals soliciting responses from for profit and non-profit housing developers for the creation of 18 units of rental housing for seniors on the former Town Police Station site located at 40 River Street. Earlier this spring, Metro West CD was chosen! The project has many hurdles to overcome before a shovel can break ground, but we are very excited to be working with the Town of Norwell on this important community project.", "Tenancy": "Rent", "Address": "40 River Street, Norwell, MA ", "Latitutde": 42.15934, "Longitude": -70.792742 }, "geometry": { "type": "Point", "coordinates": [ -70.792742, 42.15934 ] } },
{ "type": "Feature", "properties": { "Property": "54 Eddy", "Status": "In operation, from CAN-DO merge", "Number of Units": 2.0, "Description": "This two unit property is located in West Newton. There is one 3-bedroom unit and one 2-bedroom unit. Each is occupied by formerly homeless Newton families.", "Tenancy": "Rent", "Address": "54 Eddy Street, Newton, MA 02460", "Latitutde": 42.351194, "Longitude": -71.2163 }, "geometry": { "type": "Point", "coordinates": [ -71.2163, 42.351194 ] } },
{ "type": "Feature", "properties": { "Property": "Park House", "Status": "In operation, from CAN-DO merge", "Number of Units": 3.0, "Description": "This 3 unit property is located on Pearl Street in the Newton Corner neighborhood. Each of the units contains 2 bedrooms and is occupied by formerly homeless families. One of the families moved into the property from Garfield House on of our transitional housing sites. The other two units are providing housing for formerly homeless veteran families. Funding for the project was provided in part by the City of Newton - CDBG and CPA funds.", "Tenancy": "Rent", "Address": "61 Pearl Street, Newton, MA 02458", "Latitutde": 42.358361, "Longitude": -71.187955 }, "geometry": { "type": "Point", "coordinates": [ -71.187955, 42.358361 ] } },
{ "type": "Feature", "properties": { "Property": "Veteran House", "Status": "In operation, from CAN-DO merge", "Number of Units": 2.0, "Description": "Veteran House includes 2 units, one 2-bedroom unit and one 3 bedroom unit located in the Auburndale neighborhood. It is now fully occupied by two veteran families.", "Tenancy": "Rent", "Address": "2148 Commonwealth Avenue, Auburndale, MA 02466", "Latitutde": 42.347716, "Longitude": -71.250335 }, "geometry": { "type": "Point", "coordinates": [ -71.250335, 42.347716 ] } },
{ "type": "Feature", "properties": { "Property": "Webster Street Group Residence", "Status": "In operation, from CAN-DO merge", "Number of Units": 6.0, "Description": "CAN-DO renovated an existing house and constructed a three bedroom addition on Webster Street in Auburndale to provide affordable housing for six adults with developmental disabilities. Full-time supervision in a supportive living environment is provided by Newton Wellesley Weston Committee for Community Living.", "Tenancy": "Rent", "Address": "228 Webster St, Newton, MA 02465", "Latitutde": 42.3489, "Longitude": -71.23677 }, "geometry": { "type": "Point", "coordinates": [ -71.23677, 42.3489 ] } },
{ "type": "Feature", "properties": { "Property": "Highlands Glen Condominiums", "Status": "In operation, from CAN-DO merge", "Number of Units": 1.0, "Description": "CAN-DO built two new duplexes on the Christina Street property with the Kayla A. Rosenberg house. One of these four units was sold to a moderate-income family supported by Newton's First-Time Homebuyer program, and three were sold at market rate.", "Tenancy": "Own", "Address": "92 Christina Street, Newton, MA 02464", "Latitutde": 42.306601, "Longitude": -71.212337 }, "geometry": { "type": "Point", "coordinates": [ -71.212337, 42.306601 ] } },
{ "type": "Feature", "properties": { "Property": "Kayla A Rosenberg House", "Status": "In operation, from CAN-DO merge", "Number of Units": 5.0, "Description": "Named in memory of Oak Hill bus accident victim Kayla A. Rosenberg, whose father, Newton attorney Jason Rosenberg, provided many hours of legal assistance on this project. Kayla's House provides transitional housing for five young parents and children who participate in the Newton Community Service Center's Parents Program.", "Tenancy": "Transitional", "Address": "90 Christina Street, Newton, MA 02464", "Latitutde": 42.306859, "Longitude": -71.212269 }, "geometry": { "type": "Point", "coordinates": [ -71.212269, 42.306859 ] } },
{ "type": "Feature", "properties": { "Property": "18-20 Cambria Road", "Status": "In operation, from CAN-DO merge", "Number of Units": 2.0, "Description": "In January 2003, CAN-DO purchased a two-family home on Cambria Road in West Newton, which includes one 3-bedroom and one 4-bedroom apartment. CAN-DO completed renovations and upgrades to the to heating and electrical systems and now provides affordable housing for two low-income families. CAN-DO hopes that the Cambria House will provide permanent affordable housing opportunities for, among others, tenants who graduate from the transitional housing programs at Garfield House and Kayla's House.", "Tenancy": "Rent", "Address": "18 Cambria Rd, Newton, MA 02465", "Latitutde": 42.36252, "Longitude": -71.22984 }, "geometry": { "type": "Point", "coordinates": [ -71.22984, 42.36252 ] } },
{ "type": "Feature", "properties": { "Property": "Falmouth Apartments", "Status": "In operation, from CAN-DO merge", "Number of Units": 2.0, "Description": "This site provides two units of housing at 20-22 Falmouth Road, a two-bedroom unit and a three-bedroom unit occupied by low-income families. Project developed, in part, with Newton Community Preservation Funds.", "Tenancy": "Rent", "Address": "20 Falmouth Rd, Newton, MA 02465", "Latitutde": 42.36302, "Longitude": -71.22854 }, "geometry": { "type": "Point", "coordinates": [ -71.22854, 42.36302 ] } },
{ "type": "Feature", "properties": { "Property": "Jackson Apartments", "Status": "In operation, from CAN-DO merge", "Number of Units": 2.0, "Description": "This site provides two units of housing at 163 Jackson Road, a two-bedroom unit and a three-bedroom unit occupied by low-income families. Project developed, in part, with Newton Community Preservation Funds.", "Tenancy": "Rent", "Address": "163 Jackson Rd, Newton, MA 02458", "Latitutde": 42.35815, "Longitude": -71.19543 }, "geometry": { "type": "Point", "coordinates": [ -71.19543, 42.35815 ] } },
{ "type": "Feature", "properties": { "Property": "11-13 Cambria Road", "Status": "In operation, from CAN-DO merge", "Number of Units": 2.0, "Description": "This two-family project containing two - 2 bedroom units provides housing for two low-income families. Project developed, in part, with Newton Community Preservation Funds.", "Tenancy": "Rent", "Address": "13 Cambria Rd, Newton, MA 02465", "Latitutde": 42.36267, "Longitude": -71.22944 }, "geometry": { "type": "Point", "coordinates": [ -71.22944, 42.36267 ] } },
{ "type": "Feature", "properties": { "Property": "Linden Green Homes", "Status": "In operation, from CAN-DO merge", "Number of Units": 3.0, "Description": "This five unit condominium project located at 248 Elliot Street and 12-14 Linden Street in the Upper Falls neighborhood of Newton was completed in the fall of 2007. The Elliot Street property is a renovated historic house that is listed on the National Register of Historic Places. That house contains one 1-bedroom unit and two 2-bedroom units. The duplex at the 12-14 Linden Street address contains two 3-bedroom units.", "Tenancy": "Own", "Address": "248 Elliot St, Newton, MA 02464", "Latitutde": 42.312422, "Longitude": -71.219462 }, "geometry": { "type": "Point", "coordinates": [ -71.219462, 42.312422 ] } },
{ "type": "Feature", "properties": { "Property": "Millhouse Commons Condominiums", "Status": "In operation, from CAN-DO merge", "Number of Units": 4.0, "Description": "This six unit condominium project located at 1093-1101 Chestnut Street in the Upper Falls neighborhood of Newton was completed in the fall of 2007. The development includes two duplex units, each duplex has one 2-bedroom unit and one 3-bedroom unit at the rear of the property and two detached units at the front facing the street.", "Tenancy": "Own", "Address": "1101 Chestnut St, Newton, MA 02464", "Latitutde": 42.311415, "Longitude": -71.224552 }, "geometry": { "type": "Point", "coordinates": [ -71.224552, 42.311415 ] } },
{ "type": "Feature", "properties": { "Property": "Taft Ave", "Status": "In Progress", "Number of Units": 2.0, "Description": "The project will provide housing for one homeless family currently living in transitional housing in Newton and a homeless family currently living in a motel or hotel paid for by the Commonwealth.", "Tenancy": "Rent", "Address": "54 Taft Ave, Newton, MA 02465", "Latitutde": 42.36222, "Longitude": -71.22364 }, "geometry": { "type": "Point", "coordinates": [ -71.22364, 42.36222 ] } },
{ "type": "Feature", "properties": { "Property": "10 Cambria Road", "Status": "In Progress", "Number of Units": 2.0, "Description": "The project will create two deed-restricted affordable rental units. One unit will be rented to a homeless family currently living in a motel with an income at or below 50% of the area median income and the other unit will be rented to a Newton homeless families with an income below 80% of the area median income.", "Tenancy": "Rent", "Address": "10 Cambria Rd, Newton, MA 02465", "Latitutde": 42.36242, "Longitude": -71.22947 }, "geometry": { "type": "Point", "coordinates": [ -71.22947, 42.36242 ] } }
]
}
